postgres:
  image: postgres:9.4
  environment:
    POSTGRES_USER: mobydock
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/mobydock/postgresql/data:/var/lib/postgresql/data


pgadmin:
  image: thajeztah/pgadmin4
  ports:
    - '5050:5050'
  links:
    - postgres


redis:
  image: redis:3.0
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/mobydock/redis/data:/var/lib/redis/data

mobydock:
  build: ./services/python
  command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "src.app:create_app()"
  environment:
    PYTHONUNBUFFERED: 1
  links:
    - postgres
    - redis
  volumes:
    - ./services/python:/app
  ports:
    - '8000:8000'

# backoffice:
#   build: ./services/react-backoffice
#   command: npm start
#   volumes:
#     - ./services/react-backoffice:/app
#   ports:
#     - '3000:3000'

nodejs:
  build: ./services/nodejs
  # command: npm start
  links:
    - postgres
  volumes:
    - ./services/nodejs:/www
  ports:
    - '3001:8080'
